name: Docker Image CI

on:
  push:
    branches: [ "template" ]
  pull_request:
    branches: [ "template" ]
  dispatch_workflow:

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
      with:
        config: .github/buildkit.toml
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ github.repository }}/workspace
          ghcr.io/${{ github.repository }}/workspace
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: .devcontainer/base.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        pull: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
